<?php

function ccle_redirect_menu() {
    $items = array();
    $items['ccle_redirect'] = array(
        'title' => 'CCLE Request Parameters',
        'page callback' => 'get_ccle',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
     );
    return $items;
}


function get_ccle($myarg) {

 $myvar = $_GET['var1'];
 $term = $_POST["term"];
 $subj_area = $_POST["subj_area"];
 $crsidx = $_POST["crsidx"];
 $classidx = $_POST["classidx"];

 $mymsg =  'HTTP Query String Parameter ===>'.$myvar.'<br><br>HTTP POST Variable: term ===>'.$term.'<br><br>
 HTTP POST Variable: subj_area ===>'.$subj_area.'<br><br>
 HTTP POST Variable: crsidx ===>'.$crsidx.'<br><br>
 HTTP POST Variable: classidx ===>'.$classidx.'<br><br>
 SQL Query: ===>';

 return $mymsg;

}

