<?php

function ccle_redirect_menu() {
    $items = array();
    $items['redirect/ccle'] = array(
        'title' => 'CCLE Request Parameters',
        'page callback' => 'ccle_redirect_list',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
     );
    return $items;
}

function ccle_redirect_list() {

    $term_submitted = $_GET['c0']['t'];
    $subject_submitted = $_GET['c0']['sub'];
    $category_submitted = $_GET['c0']['cat'];
    $section_submitted = $_GET['c0']['sec'];

    $term_submitted = str_replace(' ', '', $term_submitted);
    $subject_submitted = str_replace(' ', '', $subject_submitted);
    $category_submitted = str_replace(' ', '', $category_submitted);
    $section_submitted = str_replace(' ', '', $section_submitted);

    $term_submitted = str_replace('%20', '', $term_submitted);
    $subject_submitted = str_replace('%20', '', $subject_submitted);
    $category_submitted = str_replace('%20', '', $category_submitted);
    $section_submitted = str_replace('%20', '', $section_submitted);

//    krumo($_GET);
//    krumo($term_submitted);

  $output = '';

  // Get all entries in the rc_res_rules table.
  if ($entries = ccle_redirect_entry_load($subject_submitted)) {
    $rows = array();
    foreach ($entries as $entry) {
    // Sanitize the data before handing it off to the theme layer.
    $rows[] = array_map('check_plain', (array) $entry);
    }

    $error_term = t('No Lib-Guides for this term have been added yet.'); // display on _menu page to user

    $rd_subj = '';
    $rd_crs = '';
    $rd_class = '';
    foreach ($rows as $row) {
        if( $row['term'] == $term_submitted ){
            $error_term = '';
            if( strlen( $row['crsidx'] ) > 0 ){
                if( $row['crsidx'] == $category_submitted ){
                    if( strlen( $row['classidx'] ) > 0 ){
                        if( $row['classidx'] == $section_submitted ){
                            $rd_class = $row['lib_guide'];
                        } else{
                        }
                    } else {
                        $rd_crs = $row['lib_guide'];
                    }
                } else {
                    $rd_subj = $row['lib_guide'];
                }
            } else {
                $rd_subj = $row['lib_guide'];
            }
        }
    }

    // cycle through redirect_subj, crs and class and branch accordingly
    if( strlen( $rd_class ) > 0 ){
        drupal_goto( $path = $rd_class );
    } elseif( strlen( $rd_crs ) > 0 ) {
        drupal_goto( $path = $rd_crs );
    } elseif ( strlen( $rd_subj ) > 0 ) {
        drupal_goto( $path = $rd_subj );
    } else {
        $error_no_guide = t('No Lib-Guides have been added yet.'); // display on _menu page to user
    }

    // test only, this will not display if the rediect happens
    // Make a table for them.
    $header = array(t('Pid'), t('term'), t('subj_area'), t('crsidx'), t('classidx'), t('lib_guide'));
    $output .= theme('table', array('header' => $header, 'rows' => $rows));
  } else {
        $error_no_guide = t('No Lib-Guides have been added yet.'); // display on _menu page to user
        //drupal_set_message(t('No Lib-Guides have been added yet.')); // display on _menu page to user
  }
$output .= 'myVars = '.$term_submitted.' '.$subject_submitted.' '.$category_submitted.' '.$section_submitted.' === '.$rd_subj.' '.$rd_crs.' '.$rd_class;
return $output;
}

/**
 * Read from the database using a filter array.
 *
 */
function ccle_redirect_entry_load($entry = array()) {
    //print_r("===>".$entry);
    //Read all fields from the rc_res_rules table.
    $query = db_select('ccle_redirect','u');
    $query
    ->condition('u.subj_area',$entry,'=')
    ->fields('u',array('pid','term','subj_area','crsidx','classidx','lib_guide'))
    ->range(0,50);
    $result=$query->execute();

    //print_r($result);
    //    while( $record = $result->fetchAssoc() ) {
    //        print_r($record);
    //    }
return $result;
}
